Feature/milestone5
Dipeshtwis/calculator pull request #4
Opened 2020-12-12 20:07 UTC by Dipeshtwis

What does this PR do:

- Implemented react prop functionality
- Implemented handleClick function
- Added onClick event to all button
- Added style to calculator

2020-12-12 21:21 UTC, christianotieno requested changes
### Changes Required ♻️  
Hello @Dipeshtwis 👋 

The hard work done on this project is commendable and congratulations on reaching this far. Your passion for software development showing with these projects, 🔥 keep it up 💯 

I have come to admire how you have made your repositories to be professional-looking from the strict adherence to the git-flow workflow, to the commits as well. The codebase looks solid and there is a decent use of the convention-based coding when working with React. Good job. 👏 

We can improve on this further, still. Please find below some comments on areas that we can address before proceeding down below, 👇 thank you!
## Required Change 
- [x] We have some commented out code in our main `index.js` module. Kindly remove them. If you need to review a previous version of your code, you can always use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))  
##

### Happy coding 💻 

#### Christian Otieno (TSE)

2020-12-12 21:21 UTC, christianotieno commented on src/components/App.js
>  /* eslint-enable no-unused-vars */
## [OPTIONAL] Stretch Requirement

- [ ] By disabling ESLint rules,  don't you think it rids you the opportunity to write much cleaner code and suppresses the potential warnings you’d be getting, thus missing out on the education that ESLint rules provide? 😟  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no-ignore-linters.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/)).

2020-12-12 21:21 UTC, christianotieno commented on src/components/ButtonPanel.js
>  /* eslint-disable no-unused-vars */
## [OPTIONAL] Stretch Requirement

- [ ] By disabling ESLint rules,  don't you think it rids you the opportunity to write much cleaner code and suppresses the potential warnings you’d be getting, thus missing out on the education that ESLint rules provide? 😟  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no-ignore-linters.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/)).

2020-12-12 21:21 UTC, christianotieno commented on src/components/Display.js
> +const Display = (props) => <h2 className ='input-value'>{props.result || props.next || '0'}</h2>;
## Optional 
- [ ] The UI isn't great when it comes to the displaying of what's to get rendered.
While we do have our function store and the next value typed, the characters never get displayed, and the user never gets to see what they keyed; a bad User Experience. Would you mind changing it up a bit (in terms of the display), a user to see the digits (and, hopefully, operations that get typed for great User experience?  This is what we currently have 👇 
![calculator](https://user-images.githubusercontent.com/22345961/101994900-287f5200-3cd7-11eb-9197-b81c8d08890b.gif)

2020-12-12 21:21 UTC, christianotieno commented on src/components/Button.js
> +/* eslint-disable no-unused-vars */
## [OPTIONAL] Stretch Requirement

- [ ] By disabling ESLint rules,  don't you think it rids you the opportunity to write much cleaner code and suppresses the potential warnings you’d be getting, thus missing out on the education that ESLint rules provide? 😟  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no-ignore-linters.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/)).

2020-12-12 21:21 UTC, christianotieno commented on src/components/ButtonPanel.js
> -/* eslint-enable no-unused-vars */
## [OPTIONAL] Stretch Requirement

- [ ] By disabling ESLint rules,  don't you think it rids you the opportunity to write much cleaner code and suppresses the potential warnings you’d be getting, thus missing out on the education that ESLint rules provide? 😟  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no-ignore-linters.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/)).

2020-12-13 14:21 UTC, Dipeshtwis commented
The Update project includes:-

- Remove all the unnecessary comment and code

2020-12-13 14:43 UTC, christianotieno approved these changes
### Project Approved 🍾 
Hello @Dipeshtwis 👋 

You have made the required changes needed for approval. Congratulations!
I wish you all the best in the next challenge 🥇 

### Happy coding 💻 
#### Christian Otieno (TSE)

2020-12-13 15:27 UTC, merged